// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAASYBfWBdb6hC8VcUdZO5FIkeZxWQQSY8',
    appId: '1:929728896505:web:f9bcb3ce8619e14f02f128',
    messagingSenderId: '929728896505',
    projectId: 'praktikum9-cd969',
    authDomain: 'praktikum9-cd969.firebaseapp.com',
    storageBucket: 'praktikum9-cd969.appspot.com',
    measurementId: 'G-7QG9GTVQH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVe-CZgbsauuYXJJmwOdO-DePkPDpTSzo',
    appId: '1:929728896505:android:5d400faee7c3898702f128',
    messagingSenderId: '929728896505',
    projectId: 'praktikum9-cd969',
    storageBucket: 'praktikum9-cd969.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv25dpmvdbV-rDF5L3HrPhIzaN5TTBGKQ',
    appId: '1:929728896505:ios:9d0bcfa7c2e8c42502f128',
    messagingSenderId: '929728896505',
    projectId: 'praktikum9-cd969',
    storageBucket: 'praktikum9-cd969.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv25dpmvdbV-rDF5L3HrPhIzaN5TTBGKQ',
    appId: '1:929728896505:ios:3cdcab5b80cee4cb02f128',
    messagingSenderId: '929728896505',
    projectId: 'praktikum9-cd969',
    storageBucket: 'praktikum9-cd969.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
